Add cv-x-if
 - Add x_disp module to offload instructions
 - Add cv-x-if memory interface in ex_stage
 - Adapt Makefile to run custom programs and embench programs using the fpu_ss
 - Add embench folder to /example_tb/scripts to automatically build embench programs when needed
 - Add cv32e40p_core_and_coprocessor_wrapper that contains an instantiatio of the fpu_ss if the parameter FPU = 1
 - Adapt LEC script

Signed-off-by: Moritz Imfeld <moimfeld@student.ethz.ch>

diff --git a/example_tb/core/Makefile b/example_tb/core/Makefile
--- a/example_tb/core/Makefile
+++ b/example_tb/core/Makefile
@@ -18,60 +18,85 @@
 # Description: Makefile for running the following examples:
 #
 #              - 'Hello World' (custom), command line 'make custom-vsim-run'
-#              - 'Floating Point example' (custom_fp), command line 'make custom-fp-vsim-run'
 #              - 'Interrupt example' (interrupt), command line 'make interrupt-vsim-run'
+#
+#			   Floating-Point:
+#					RISCV variable must be set to the path of the compiler
+#					EXTENSION variable must be set to either 'f' or 'zfinx'
+#					PROGRAM_PATH variable must be set or the PROGRAM variable
+#						must be set to valid option. Valid programs are:
+#						matmul, aha-mont64, crc32, cubic, edn, huffbench, matmult-int,
+#						minver, nbody, nettle-aes, nettle-sha256, nsichneu, picojpeg,
+#						qrduino, sglib-combined, slre, st, statemate, ud, wikisort
+#
+#					Example: 'make custom-fp-vsim-run EXTENSION=f PROGRAM=minver'
+#
+#					Notes:	- If the fpu_ss has not yet been cloned, 'make fpu_ss_deps'
+#							  must be run.
+#							- If an Embench program is chosen, the repository is
+#							  cloned and the programs are built automatically.
+
 
 MAKE			= make
 
 # vsim configuration
-VVERSION                = "10.7b"
+VVERSION		= "10.7b"
 
 VLIB			= vlib-$(VVERSION)
 VWORK			= work
 
 VLOG			= vlog-$(VVERSION)
 VLOG_FLAGS		= -pedanticerrors -suppress 2577 -suppress 2583 -define CV32E40P_TRACE_EXECUTION
-VLOG_LOG                = vloggy
+VLOG_LOG		= vloggy
 
 VOPT			= vopt-$(VVERSION)
 VOPT_FLAGS		= -debugdb -fsmdebug -pedanticerrors +acc #=mnprft
 
 VSIM			= vsim-$(VVERSION)
-VSIM_HOME               = /usr/pack/modelsim-$(VVERSION)-kgf/questasim
-VSIM_FLAGS              =  # user defined
+VSIM_HOME		= /usr/pack/modelsim-$(VVERSION)-kgf/questasim
+VSIM_FLAGS		=  # user defined
 ALL_VSIM_FLAGS		= $(VSIM_FLAGS)
 VSIM_DEBUG_FLAGS	= -debugdb
-VSIM_GUI_FLAGS          = -gui -debugdb
-VSIM_SCRIPT             = vsim.tcl
+VSIM_GUI_FLAGS		= -gui -debugdb
+VSIM_SCRIPT		= vsim.tcl
 
 # RTL source files
-RTLSRC_HOME             := ../..
-export DESIGN_RTL_DIR = $(RTLSRC_HOME)/rtl
-CV_CORE_MANIFEST    := $(RTLSRC_HOME)/cv32e40p_manifest.flist
+export RTLSRC_HOME	:= $(shell pwd)/../..
+export DESIGN_RTL_DIR	 = $(RTLSRC_HOME)/rtl
+CV_CORE_MANIFEST	:= $(RTLSRC_HOME)/cv32e40p_manifest.flist
 RTLSRC_TB_PKG		:= include/perturbation_pkg.sv
 RTLSRC_TB_TOP		:= tb_top.sv
-RTLSRC_TB		:= $(filter-out cv32e40p_fp_wrapper.sv,\
-				$(wildcard *.sv))
+RTLSRC_TB		:= $(wildcard *.sv))
 
-RTLSRC_FPNEW_TB		:= $(wildcard *.sv)
-RTLSRC_FPNEW_INCDIR	:= $(RTLSRC_HOME)/rtl/fpnew/src/common_cells/include
-RTLSRC_FPNEW_PKG	:= $(RTLSRC_HOME)/rtl/fpnew/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv $(RTLSRC_HOME)/rtl/fpnew/src/fpnew_pkg.sv $(RTLSRC_HOME)/rtl/fpnew/src/common_cells/src/cf_math_pkg.sv
-RTLSRC_FPNEW		:= $(filter-out $(RTLSRC_HOME)/rtl/fpnew/src/fpnew_pkg.sv, $(wildcard $(RTLSRC_HOME)/rtl/fpnew/src/*.sv)) \
-				$(filter-out $(RTLSRC_HOME)/rtl/fpnew/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv, $(wildcard $(RTLSRC_HOME)/rtl/fpnew/src/fpu_div_sqrt_mvp/hdl/*.sv)) \
-				 $(RTLSRC_HOME)/rtl/fpnew/src//common_cells/src/rr_arb_tree.sv  $(RTLSRC_HOME)/rtl/fpnew/src/common_cells/src/lzc.sv
+RTLSRC_CV_X_IF_TB		:=  $(wildcard *.sv) $(wildcard $(RTLSRC_HOME)/rtl/fpu_ss/src/*.sv) $(wildcard $(RTLSRC_HOME)/rtl/fpu_ss/bhv/*.sv)
+RTLSRC_CV_X_IF_INCDIR		:=
+RTLSRC_COMMON_CELLS_INCDIR	:= $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/include
+RTLSRC_CV_X_IF_PKG		:= $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/src/cf_math_pkg.sv \
+				   $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/fpnew_pkg.sv $(wildcard $(RTLSRC_HOME)/rtl/fpu_ss/src/*pkg.sv)\
+				   $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
+RTLSRC_CV_X_IF			:= $(filter-out $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/src/cf_math_pkg.sv\
+				   $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/src/cb_filter.sv $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/src/ecc_encode.sv \
+				   $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/src/ecc_decode.sv,\
+				   $(wildcard $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/src/*.sv) $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/common_cells/src/deprecated/fifo_v2.sv \
+				   $(wildcard $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/*.sv) $(wildcard $(RTLSRC_HOME)/rtl/fpu_ss/fpnew/src/fpu_div_sqrt_mvp/hdl/*.sv))
 
 RTLSRC_VLOG_TB_TOP	:= $(basename $(notdir $(RTLSRC_TB_TOP)))
 RTLSRC_VOPT_TB_TOP	:= $(addsuffix _vopt, $(RTLSRC_VLOG_TB_TOP))
 
-# riscv toolchain install path
-RISCV                    ?= ~/.riscv
-RISCV_EXE_PREFIX         = $(RISCV)/bin/riscv32-unknown-elf-
+# riscv toolchain install path and flags
+RISCV			?= ~/.riscv
+export RISCV_EXE_PREFIX	 = $(RISCV)/bin/riscv32-unknown-elf-
+
+EXTENSION 	?= not_set
+PROGRAM 	?= matmul
+PROGRAM_PATH 	 =
+
 
 # assume vsim if no target chosen
 .DEFAULT_GOAL := custom-vsim-run
 
 # GCC configuration
-CUSTOM_GCC_FLAGS           =
+CUSTOM_GCC_FLAGS =
 
 all: custom-vsim-run
 
@@ -95,26 +120,6 @@ vsim-all: .opt-rtl
 	$(RTLSRC_VOPT_TB_TOP)
 	touch .opt-rtl
 
-# fpnew dependencies
-check_fpnew_deps:
-	@if [ ! -d ../../rtl/fpnew ]; then echo Please run \'make fpnew_deps\' first to clone the required fpnew repos; exit 1; fi
-
-fpnew_deps:
-	if [ ! -d ../../rtl/fpnew ]; then git clone https://github.com/pulp-platform/fpnew ../../rtl/fpnew --recurse; fi
-
-# rebuild if we change some sourcefile
-.build-rtl-fp: .lib-rtl $(RTLSRC_FPNEW_PKG) $(RTLSRC_FPNEW) $(CV_CORE_MANIFEST) $(RTLSRC_TB_PKG) $(RTLSRC_FPNEW_TB)
-	$(VLOG) -work $(VWORK) +incdir+$(RTLSRC_FPNEW_INCDIR) $(VLOG_FLAGS) \
-	 $(RTLSRC_FPNEW_PKG) $(RTLSRC_FPNEW) -f $(CV_CORE_MANIFEST) $(RTLSRC_TB_PKG) $(RTLSRC_FPNEW_TB)
-	touch .build-rtl-fp
-
-vsim-all-fp: check_fpnew_deps .opt-rtl-fp
-
-.opt-rtl-fp: .build-rtl-fp
-	$(VOPT) -work $(VWORK) $(VOPT_FLAGS) -g FPU=1 $(RTLSRC_VLOG_TB_TOP) -o \
-	$(RTLSRC_VOPT_TB_TOP)
-	touch .opt-rtl-fp
-
 vsim-all-pulp: .opt-rtl-pulp
 
 .opt-rtl-pulp: .build-rtl
@@ -122,6 +127,83 @@ vsim-all-pulp: .opt-rtl-pulp
 	$(RTLSRC_VOPT_TB_TOP)
 	touch .opt-rtl-pulp
 
+# check if fpu_ss is already clones
+check_fpu_ss_deps:
+	@if [ ! -d ../../rtl/fpu_ss ]; then echo Please run \'make fpu_ss_deps\' first to clone the required fpu_ss repos; exit 1; fi
+
+# clone fpu_ss, checkout correct commit and apply a patch
+fpu_ss_deps:
+	if [ ! -d ../../rtl/fpu_ss ];then git clone https://github.com/moimfeld/fpu_ss $(RTLSRC_HOME)/rtl/fpu_ss --recurse-submodules;\
+	fi
+
+# check and set environment variables
+.PHONY: check_variables
+check_variables:
+ifndef RISCV
+	$(error RISCV variable not set. (set it to the path of your compiler))
+endif
+ifeq ($(EXTENSION),f)
+  BUILD_DEFINE := FPU_SS_TRACER
+  PULP_ZFINX   := 0
+  export MARCH := rv32imfc
+  export MABI  := ilp32f
+else ifeq ($(EXTENSION),zfinx)
+  BUILD_DEFINE := PULP_ZFINX_DEF+FPU_SS_TRACER
+  PULP_ZFINX   := 1
+  export MARCH := rv32imczfinx
+  export MABI  := ilp32
+else
+	$(error EXTENSION variable not valid. (set it to 'f' or 'zfinx'))
+endif
+ifeq ($(PROGRAM),matmul)
+  PROGRAM_PATH := custom_fp/matmulNxN.c custom_fp/main.c
+else ifneq (,$(filter $(PROGRAM),aha-mont64 crc32 cubic edn huffbench matmult-int minver nbody nettle-aes nettle-sha256 nsichneu picojpeg qrduino sglib-combined slre st statemate ud wikisort))
+  PROGRAM_PATH := embench-iot/bd/src/$(PROGRAM)/$(PROGRAM)
+else ifndef PROGRAM_PATH
+	$(error PROGRAM_PATH variable not set. Either set the variable directly or choose a valid program. Valid programs are: matmul, aha-mont64, crc32, cubic, edn, huffbench, matmult-int, minver, nbody, nettle-aes, nettle-sha256, nsichneu, picojpeg, qrduino, sglib-combined, slre, st, statemate, ud, wikisort)
+endif
+
+# clone embench and build programs
+.PHONY: check_embench
+check_embench:
+ifneq (,$(filter $(PROGRAM),aha-mont64 crc32 cubic edn huffbench matmult-int minver nbody nettle-aes nettle-sha256 nsichneu picojpeg qrduino sglib-combined slre st statemate ud wikisort))
+	if [ ! -d embench-iot ]; then git clone https://github.com/embench/embench-iot;\
+		cd embench-iot;\
+		git checkout b2cb4ba;\
+		python3 ../../scripts/embench/change_patch.py;\
+		git apply ../../scripts/embench/tmp.patch;\
+		./../../scripts/embench/build.sh;\
+		cd -;\
+		cp -v $(PROGRAM_PATH) custom_fp/fp_program.elf;\
+	fi
+	if [ ! -d embench-iot/bd ]; then cd embench-iot;\
+		python3 ../../scripts/embench/change_patch.py;\
+		git checkout config/riscv32/* src/*;\
+		git checkout b2cb4ba;\
+		git apply ../../scripts/embench/tmp.patch;\
+		./../../scripts/embench/build.sh;\
+		cd -;\
+		cp -v $(PROGRAM_PATH) custom_fp/fp_program.elf;\
+	fi
+endif
+
+embench_clean:
+	rm embench-iot/bd -r
+
+
+vsim-all-fp: check_fpu_ss_deps .opt-fp-rtl
+
+# rebuild if we change some sourcefile
+.build-fp-rtl: .lib-rtl $(RTLSRC_CV_X_IF_PKG) $(RTLSRC_CV_X_IF) $(CV_CORE_MANIFEST) $(RTLSRC_TB_PKG) $(RTLSRC_CV_X_IF_TB)
+	$(VLOG) -work $(VWORK) +define+$(BUILD_DEFINE) +incdir+$(RTLSRC_CV_X_IF_INCDIR)+$(RTLSRC_COMMON_CELLS_INCDIR) $(VLOG_FLAGS) \
+	 $(RTLSRC_CV_X_IF_PKG) $(RTLSRC_CV_X_IF) -f $(CV_CORE_MANIFEST) $(RTLSRC_TB_PKG) $(RTLSRC_CV_X_IF_TB)
+	touch .build-fp-rtl
+
+# rebuild cv_x_if
+.opt-fp-rtl: .build-fp-rtl
+	$(VOPT) -work $(VWORK) $(VOPT_FLAGS) -g FPU=1 -g PULP_ZFINX=$(PULP_ZFINX) $(RTLSRC_VLOG_TB_TOP) -o \
+	$(RTLSRC_VOPT_TB_TOP)
+	touch .opt-fp-rtl
 
 # run tb and exit
 .PHONY: vsim-run
@@ -148,28 +230,7 @@ vsim-run-gui: vsim-all
 tb-clean:
 	if [ -d $(VWORK) ]; then rm -r $(VWORK); fi
 	rm -f transcript vsim.wlf vsim.dbg trace_core*.log \
-	.build-rtl .opt-rtl .lib-rtl *.vcd objdump
-
-# run tb and exit
-.PHONY: vsim-run-fp
-vsim-run-fp: ALL_VSIM_FLAGS += -c
-vsim-run-fp: vsim-all-fp
-	$(VSIM) -work $(VWORK) $(ALL_VSIM_FLAGS) -GFPU=1 \
-	$(RTLSRC_VOPT_TB_TOP) -do 'source $(VSIM_SCRIPT); exit -f'
-
-# run tb and drop into interactive shell
-.PHONY: vsim-run-sh-fp
-vsim-run-sh-fp: ALL_VSIM_FLAGS += -c
-vsim-run-sh-fp: vsim-all-fp
-	$(VSIM) -work $(VWORK) $(ALL_VSIM_FLAGS) \
-	$(RTLSRC_VOPT_TB_TOP) -do $(VSIM_SCRIPT)
-
-# run tb with simulator gui
-.PHONY: vsim-run-gui-fp
-vsim-run-gui-fp: ALL_VSIM_FLAGS += $(VSIM_GUI_FLAGS)
-vsim-run-gui-fp: vsim-all-fp
-	$(VSIM) -work $(VWORK) $(ALL_VSIM_FLAGS) -GFPU=1 \
-	$(RTLSRC_VOPT_TB_TOP) -do $(VSIM_SCRIPT)
+	.build-rtl .build-fp-rtl .opt-rtl .opt-fp-rtl .lib-rtl *.vcd objdump
 
 # run tb and exit
 .PHONY: vsim-run-pulp
@@ -186,18 +247,29 @@ vsim-run-gui-pulp: vsim-all-pulp
 	$(VSIM) -work $(VWORK) $(ALL_VSIM_FLAGS) -GPULP_XPULP=1 \
 	$(RTLSRC_VOPT_TB_TOP) -do $(VSIM_SCRIPT)
 
-.PHONY: tb-clean-fp
-tb-clean-fp:
-	if [ -d $(VWORK) ]; then rm -r $(VWORK); fi
-	rm -rf transcript vsim.wlf vsim.dbg trace_core*.log \
-	.build-rtl-fp .opt-rtl-fp .lib-rtl-fp *.vcd objdump
+# run tb
+.PHONY: vsim-fp-run
+vsim-fp-run: ALL_VSIM_FLAGS += -c
+vsim-fp-run: vsim-all-fp
+	$(VSIM) -work $(VWORK) $(ALL_VSIM_FLAGS) -GFPU=1 \
+	$(RTLSRC_VOPT_TB_TOP) -do $(VSIM_SCRIPT)
+
+# run tb with simulator gui
+.PHONY: vsim-fp-run-gui
+vsim-fp-run-gui: ALL_VSIM_FLAGS += $(VSIM_GUI_FLAGS)
+vsim-fp-run-gui: vsim-all-fp
+	$(VSIM) -work $(VWORK) $(ALL_VSIM_FLAGS) -GFPU=1 \
+	$(RTLSRC_VOPT_TB_TOP) -do $(VSIM_SCRIPT)
 
 # rules to generate hex (loadable by simulators) from elf
 %.hex: %.elf
 	$(RISCV_EXE_PREFIX)objcopy -O verilog $< $@
 
 %.dis: %.elf
-	$(RISCV_EXE_PREFIX)objdump -S $^
+	$(RISCV_EXE_PREFIX)objdump -S $^ > $@
+
+%.dump: %.elf
+	$(RISCV_EXE_PREFIX)objdump -xD $^ > $@
 
 
 # Running custom programs:
@@ -211,12 +283,12 @@ custom/hello_world.elf: custom/hello_world.c
 		-static \
 		custom/crt0.S \
 		$^ mem_stall/mem_stall.c custom/syscalls.c custom/vectors.S \
-		-I $(RISCV)/riscv32-unknown-elf/include \
+		-I $(RISCV)/riscv32-corev-elf/include \
 		-I mem_stall \
-		-L $(RISCV)/riscv32-unknown-elf/lib \
+		-L $(RISCV)/riscv32-corev-elf/lib \
 		-lc -lm -lgcc
 custom-clean:
-	rm -rf custom/hello_world.elf custom/hello_world.hex
+	rm -rf custom/hello_world.elf custom/hello_world.hex custom/hello_world.dis custom/hello_world.dump
 
 .PHONY: custom-vsim-run
 custom-vsim-run: vsim-all custom/hello_world.hex
@@ -228,33 +300,29 @@ custom-vsim-run-gui: vsim-all custom/hello_world.hex
 custom-vsim-run-gui: ALL_VSIM_FLAGS += "+firmware=custom/hello_world.hex"
 custom-vsim-run-gui: vsim-run-gui
 
-# Running custom fp programs:
-# This is an example for running a floating-point matrix multiplication in the testbench
-# We link with our custom crt0.s and syscalls.c against newlib so that we can
-# use the c standard library
-custom_fp/main.elf: custom_fp/matmulNxN.c custom_fp/main.c
-	$(RISCV_EXE_PREFIX)gcc -march=rv32imfc -mabi=ilp32f -o $@ -w -g -nostdlib \
+custom_fp/fp_program.elf: $(PROGRAM_PATH)
+	$(RISCV_EXE_PREFIX)gcc -march=$(MARCH) -mabi=$(MABI) -o $@ -w -g -nostdlib \
 		$(CUSTOM_GCC_FLAGS) \
-		-T custom/link.ld  \
+		-T custom/link.ld \
 		-static \
 		custom/crt0.S \
-		$^ custom/syscalls.c custom/vectors.S \
+		$^  custom/syscalls.c custom/vectors.S \
 		-I $(RISCV)/riscv32-unknown-elf/include \
-		-L $(RISCV)/riscv32-unknown-elf/lib \
 		-lc -lm -lgcc
+
 custom-fp-clean:
-	rm -rf custom_fp/main.elf custom_fp/main.hex
+	rm -rf custom_fp/fp_program.elf custom_fp/fp_program.hex custom_fp/fp_program.dis custom_fp/fp_program.dump
 
 .PHONY: custom-fp-vsim-run
-custom-fp-vsim-run: vsim-all-fp custom_fp/main.hex
-custom-fp-vsim-run: ALL_VSIM_FLAGS += "+firmware=custom_fp/main.hex"
-custom-fp-vsim-run: vsim-run-fp
-
+custom-fp-vsim-run: check_variables check_embench vsim-all-fp custom_fp/fp_program.hex custom_fp/fp_program.dis custom_fp/fp_program.dump
+custom-fp-vsim-run: ALL_VSIM_FLAGS += "+firmware=custom_fp/fp_program.hex"
+custom-fp-vsim-run: vsim-fp-run
 
 .PHONY: custom-fp-vsim-run-gui
-custom-fp-vsim-run-gui: vsim-all-fp custom_fp/main.hex
-custom-fp-vsim-run-gui: ALL_VSIM_FLAGS += "+firmware=custom_fp/main.hex"
-custom-fp-vsim-run-gui: vsim-run-gui-fp
+custom-fp-vsim-run-gui: check_variables check_embench vsim-all-fp custom_fp/fp_program.hex custom_fp/fp_program.dis custom_fp/fp_program.dump
+custom-fp-vsim-run-gui: ALL_VSIM_FLAGS += "+firmware=custom_fp/fp_program.hex"
+custom-fp-vsim-run-gui: vsim-fp-run-gui
+
 
 # compile and run interrupt
 interrupt/interrupt.elf: interrupt/interrupt.c
@@ -312,4 +380,5 @@ hwlp-vsim-run-gui: vsim-run-gui-pulp
 
 # general targets
 .PHONY: clean
-clean: tb-clean tb-clean-fp custom-clean custom-fp-clean interrupt-clean hwlp-clean
+clean: tb-clean custom-clean interrupt-clean hwlp-clean custom-fp-clean embench_clean
+
